### ISSUE TITLE
HTML to-do list

### ISSUE THREAD

**Issue by buraksyagmur** [buraksyagmur/real-time-forum#4]
- [ ] Feed Display
- [ ] Online/Offline Section
- [ ] Log Out button
- [x] Login / Register pop-up screen
- [ ] clickable posts - open small window
- [ ] clickable peoples, open small window
